#!/usr/bin/sh

active="$(hyprctl activeworkspace | sed 2,9d | awk -F" " '{print $3}' | tr -cd '[[:digit:]]')"

ws1=1
ws2=2
ws3=3
ws4=4

acws="background-color: rgb(195,195,195); padding: 0px 5px 0px 5px; color: rgb(44,44,52);"

if [ "$1" == "acws1" ] && [ $active == 1 ]; then
	echo "$acws"
elif [ "$1" == "acws2" ] && [ $active == 2 ]; then
	echo $acws
elif [ "$1" == "acws3" ] && [ $active == 3 ]; then
	echo $acws
elif [ "$1" == "acws4" ] && [ $active == 4 ]; then
	echo $acws
fi
